#ifndef HeavyFlavorAnalysis_BsToJpsiPhi_BsToJpsiPhiRootTree_h
#define HeavyFlavorAnalysis_BsToJpsiPhi_BsToJpsiPhiRootTree_h

#include <string>
#include <TROOT.h>
#include <TTree.h>
#include <TFile.h>
#include <TChain.h>
#include <vector>

class BsToJpsiPhiRootTree {
public:

  BsToJpsiPhiRootTree();

  ~BsToJpsiPhiRootTree();

  void resetEntries();
  void writeFile();
  void createTree(const std::string filename);

  // read tree from single file
  void readTree(const std::string filename);

  // read tree as chain from multiple files
  void readTree(std::vector<std::string> filenames);


  void getAngles(const double aa, const double bb, const double cc, const double dd);
  void getVtx(const double aa, const double bb, const double cc, const double dd, const double ee, const double ff, const double gg, const double hh, const double ii);


  void getDeDx(const double f1, const double f2, const int f3);

  void fill();

  void setBranchAddresses();
public:
  int BplusCharge_;
  double BplusMu1Eta_;
  double BplusMu2Eta_;
  int BpSoftMuon1_;
  int BpSoftMuon2_;	
  double JpsiPtbplus_fit_;

  //BEGIN Muon Taggging
  int    BpTagGENID_;
  int    BpTag_;
  double BpTagP_;
  double BpTagPt_;
  double BpTagEta_;
  double BpTagPhi_;
  double BpTagIP_;
  int    BpTagCharge_;
  int    BpTagPF_;
  int    BpTagLoose_;
  int    BpTagSoft_;
  int    BpTagTight_;
  int    BpTagTracker_;
  int    BpTagGlobal_;
  int    BpTagGlobalPromptTight_;
  int    BpTagTrackerArbitrated_;
  double BpTagGlbNormChi2_;
  int    BpTagGlbValidMuonHits_;
  int    BpTagInTrkNValidHits_;
  int    BpTagInTrkNValidPixelHits_;
  double BpTagInTrkNormChi2_;
  int    BpTagNMatches_;
  int    BpTagNMatchedStations_;
  int    BpTagNTrkLayersWithMeas_;
  int    BpTagIsolationValid_;
  int    BpTagPFIsolationValid_;
  double BpTagPFIsolationR04SumChHadPt_;
  double BpTagPFIsolationR04SumChParPt_;
  double BpTagPFIsolationR04SumNeuHadEt_;
  double BpTagPFIsolationR04SumPhoEt_;
  double BpTagPFIsolationR04SumPUPt_;
  double BpTagPFIsoR04Rel_;
  double BpTagPFIsoR04RelPUcorr_;
  double BpTagDxyz_;
  double BpTagDxyzErr_;
  double BpTagDxy_;
  double BpTagDxyErr_;
  int    BpTagChargeDiffRecoB_;
  int    BpTagCPDiffGenB_;
  double BpTagBDeltaR_;
  double BpTagMuJetDeltaR_;
  double BpTagMuJetPtRel_;
  double BpTagMuJetPOverE_;
  double BpTagMuJetPtOverE_;
  double BpTagMuJetPtOverPt_;
  double BpTagChargeConeMuInR03K025_;
  double BpTagChargeConeMuInR03K050_;
  double BpTagChargeConeMuInR03K075_;
  double BpTagChargeConeMuInR03K100_;
  double BpTagChargeConeMuInR03K110_;
  double BpTagChargeConeMuInR03K125_;
  double BpTagChargeConeMuInR03K150_;
  double BpTagChargeConeMuInR03K175_;
  double BpTagChargeConeMuOutR03K025_;
  double BpTagChargeConeMuOutR03K050_;
  double BpTagChargeConeMuOutR03K075_;
  double BpTagChargeConeMuOutR03K100_;
  double BpTagChargeConeMuOutR03K110_;
  double BpTagChargeConeMuOutR03K125_;
  double BpTagChargeConeMuOutR03K150_;
  double BpTagChargeConeMuOutR03K175_;
  double BpTagChargeConeMuInR05K025_;
  double BpTagChargeConeMuInR05K050_;
  double BpTagChargeConeMuInR05K075_;
  double BpTagChargeConeMuInR05K100_;
  double BpTagChargeConeMuInR05K110_;
  double BpTagChargeConeMuInR05K125_;
  double BpTagChargeConeMuInR05K150_;
  double BpTagChargeConeMuInR05K175_;
  double BpTagChargeConeMuOutR05K025_;
  double BpTagChargeConeMuOutR05K050_;
  double BpTagChargeConeMuOutR05K075_;
  double BpTagChargeConeMuOutR05K100_;
  double BpTagChargeConeMuOutR05K110_;
  double BpTagChargeConeMuOutR05K125_;
  double BpTagChargeConeMuOutR05K150_;
  double BpTagChargeConeMuOutR05K175_;
  double BpTagChargeConeMuInR03K025PV_;
  double BpTagChargeConeMuInR03K050PV_;
  double BpTagChargeConeMuInR03K075PV_;
  double BpTagChargeConeMuInR03K100PV_;
  double BpTagChargeConeMuInR03K110PV_;
  double BpTagChargeConeMuInR03K125PV_;
  double BpTagChargeConeMuInR03K150PV_;
  double BpTagChargeConeMuInR03K175PV_;
  double BpTagChargeConeMuOutR03K025PV_;
  double BpTagChargeConeMuOutR03K050PV_;
  double BpTagChargeConeMuOutR03K075PV_;
  double BpTagChargeConeMuOutR03K100PV_;
  double BpTagChargeConeMuOutR03K110PV_;
  double BpTagChargeConeMuOutR03K125PV_;
  double BpTagChargeConeMuOutR03K150PV_;
  double BpTagChargeConeMuOutR03K175PV_;
  double BpTagChargeConeMuInR05K025PV_;
  double BpTagChargeConeMuInR05K050PV_;
  double BpTagChargeConeMuInR05K075PV_;
  double BpTagChargeConeMuInR05K100PV_;
  double BpTagChargeConeMuInR05K110PV_;
  double BpTagChargeConeMuInR05K125PV_;
  double BpTagChargeConeMuInR05K150PV_;
  double BpTagChargeConeMuInR05K175PV_;
  double BpTagChargeConeMuOutR05K025PV_;
  double BpTagChargeConeMuOutR05K050PV_;
  double BpTagChargeConeMuOutR05K075PV_;
  double BpTagChargeConeMuOutR05K100PV_;
  double BpTagChargeConeMuOutR05K110PV_;
  double BpTagChargeConeMuOutR05K125PV_;
  double BpTagChargeConeMuOutR05K150PV_;
  double BpTagChargeConeMuOutR05K175PV_;
  double BpTagChargeConeInR03K025_;
  double BpTagChargeConeInR03K050_;
  double BpTagChargeConeInR03K075_;
  double BpTagChargeConeInR03K100_;
  double BpTagChargeConeInR03K110_;
  double BpTagChargeConeInR03K125_;
  double BpTagChargeConeInR03K150_;
  double BpTagChargeConeInR03K175_;
  double BpTagChargeConeOutR03K025_;
  double BpTagChargeConeOutR03K050_;
  double BpTagChargeConeOutR03K075_;
  double BpTagChargeConeOutR03K100_;
  double BpTagChargeConeOutR03K110_;
  double BpTagChargeConeOutR03K125_;
  double BpTagChargeConeOutR03K150_;
  double BpTagChargeConeOutR03K175_;
  double BpTagChargeConeInR05K025_;
  double BpTagChargeConeInR05K050_;
  double BpTagChargeConeInR05K075_;
  double BpTagChargeConeInR05K100_;
  double BpTagChargeConeInR05K110_;
  double BpTagChargeConeInR05K125_;
  double BpTagChargeConeInR05K150_;
  double BpTagChargeConeInR05K175_;
  double BpTagChargeConeOutR05K025_;
  double BpTagChargeConeOutR05K050_;
  double BpTagChargeConeOutR05K075_;
  double BpTagChargeConeOutR05K100_;
  double BpTagChargeConeOutR05K110_;
  double BpTagChargeConeOutR05K125_;
  double BpTagChargeConeOutR05K150_;
  double BpTagChargeConeOutR05K175_;
  int    BpTagMuJet_;
  double BpTagMuJetP_;
  double BpTagMuJetPt_;
  double BpTagMuJetEta_;
  double BpTagMuJetPhi_;
  double BpTagMuJetEnergy_;
  double BpTagMuJetMass_;
  double BpTagMuJetCSV_;
  double BpTagMuJetBDeltaR_;
  int    BpTagMuJetParton_;
  int    BpTagMCCode_;
  int    BpTagMCSimpleCode_;
  int    BpTagAncestorId_;

  int    BsTagGENID_;
  int    BsTag_;
  double BsTagP_;
  double BsTagPt_;
  double BsTagEta_;
  double BsTagPhi_;
  double BsTagIP_;
  int    BsTagCharge_;
  int    BsTagPF_;
  int    BsTagLoose_;
  int    BsTagSoft_;
  int    BsTagTight_;
  int    BsTagTracker_;
  int    BsTagGlobal_;
  int    BsTagGlobalPromptTight_;
  int    BsTagTrackerArbitrated_;
  double BsTagGlbNormChi2_;
  int    BsTagGlbValidMuonHits_;
  int    BsTagInTrkNValidHits_;
  int    BsTagInTrkNValidPixelHits_;
  double BsTagInTrkNormChi2_;
  int    BsTagNMatches_;
  int    BsTagNMatchedStations_;
  int    BsTagNTrkLayersWithMeas_;
  int    BsTagIsolationValid_;
  int    BsTagPFIsolationValid_;
  double BsTagPFIsolationR04SumChHadPt_;
  double BsTagPFIsolationR04SumChParPt_;
  double BsTagPFIsolationR04SumNeuHadEt_;
  double BsTagPFIsolationR04SumPhoEt_;
  double BsTagPFIsolationR04SumPUPt_;
  double BsTagPFIsoR04Rel_;
  double BsTagPFIsoR04RelPUcorr_;
  double BsTagDxyz_;
  double BsTagDxyzErr_;
  double BsTagDxy_;
  double BsTagDxyErr_;
  int    BsTagChargeDiffRecoB_;
  int    BsTagCPDiffGenB_;
  double BsTagBDeltaR_;
  double BsTagMuJetDeltaR_;
  double BsTagMuJetPtRel_;
  double BsTagMuJetPOverE_;
  double BsTagMuJetPtOverE_;
  double BsTagMuJetPtOverPt_;
  double BsTagChargeConeMuInR03K025_;
  double BsTagChargeConeMuInR03K050_;
  double BsTagChargeConeMuInR03K075_;
  double BsTagChargeConeMuInR03K100_;
  double BsTagChargeConeMuInR03K110_;
  double BsTagChargeConeMuInR03K125_;
  double BsTagChargeConeMuInR03K150_;
  double BsTagChargeConeMuInR03K175_;
  double BsTagChargeConeMuOutR03K025_;
  double BsTagChargeConeMuOutR03K050_;
  double BsTagChargeConeMuOutR03K075_;
  double BsTagChargeConeMuOutR03K100_;
  double BsTagChargeConeMuOutR03K110_;
  double BsTagChargeConeMuOutR03K125_;
  double BsTagChargeConeMuOutR03K150_;
  double BsTagChargeConeMuOutR03K175_;
  double BsTagChargeConeMuInR05K025_;
  double BsTagChargeConeMuInR05K050_;
  double BsTagChargeConeMuInR05K075_;
  double BsTagChargeConeMuInR05K100_;
  double BsTagChargeConeMuInR05K110_;
  double BsTagChargeConeMuInR05K125_;
  double BsTagChargeConeMuInR05K150_;
  double BsTagChargeConeMuInR05K175_;
  double BsTagChargeConeMuOutR05K025_;
  double BsTagChargeConeMuOutR05K050_;
  double BsTagChargeConeMuOutR05K075_;
  double BsTagChargeConeMuOutR05K100_;
  double BsTagChargeConeMuOutR05K110_;
  double BsTagChargeConeMuOutR05K125_;
  double BsTagChargeConeMuOutR05K150_;
  double BsTagChargeConeMuOutR05K175_;
  double BsTagChargeConeMuInR03K025PV_;
  double BsTagChargeConeMuInR03K050PV_;
  double BsTagChargeConeMuInR03K075PV_;
  double BsTagChargeConeMuInR03K100PV_;
  double BsTagChargeConeMuInR03K110PV_;
  double BsTagChargeConeMuInR03K125PV_;
  double BsTagChargeConeMuInR03K150PV_;
  double BsTagChargeConeMuInR03K175PV_;
  double BsTagChargeConeMuOutR03K025PV_;
  double BsTagChargeConeMuOutR03K050PV_;
  double BsTagChargeConeMuOutR03K075PV_;
  double BsTagChargeConeMuOutR03K100PV_;
  double BsTagChargeConeMuOutR03K110PV_;
  double BsTagChargeConeMuOutR03K125PV_;
  double BsTagChargeConeMuOutR03K150PV_;
  double BsTagChargeConeMuOutR03K175PV_;
  double BsTagChargeConeMuInR05K025PV_;
  double BsTagChargeConeMuInR05K050PV_;
  double BsTagChargeConeMuInR05K075PV_;
  double BsTagChargeConeMuInR05K100PV_;
  double BsTagChargeConeMuInR05K110PV_;
  double BsTagChargeConeMuInR05K125PV_;
  double BsTagChargeConeMuInR05K150PV_;
  double BsTagChargeConeMuInR05K175PV_;
  double BsTagChargeConeMuOutR05K025PV_;
  double BsTagChargeConeMuOutR05K050PV_;
  double BsTagChargeConeMuOutR05K075PV_;
  double BsTagChargeConeMuOutR05K100PV_;
  double BsTagChargeConeMuOutR05K110PV_;
  double BsTagChargeConeMuOutR05K125PV_;
  double BsTagChargeConeMuOutR05K150PV_;
  double BsTagChargeConeMuOutR05K175PV_;
  double BsTagChargeConeInR03K025_;
  double BsTagChargeConeInR03K050_;
  double BsTagChargeConeInR03K075_;
  double BsTagChargeConeInR03K100_;
  double BsTagChargeConeInR03K110_;
  double BsTagChargeConeInR03K125_;
  double BsTagChargeConeInR03K150_;
  double BsTagChargeConeInR03K175_;
  double BsTagChargeConeOutR03K025_;
  double BsTagChargeConeOutR03K050_;
  double BsTagChargeConeOutR03K075_;
  double BsTagChargeConeOutR03K100_;
  double BsTagChargeConeOutR03K110_;
  double BsTagChargeConeOutR03K125_;
  double BsTagChargeConeOutR03K150_;
  double BsTagChargeConeOutR03K175_;
  double BsTagChargeConeInR05K025_;
  double BsTagChargeConeInR05K050_;
  double BsTagChargeConeInR05K075_;
  double BsTagChargeConeInR05K100_;
  double BsTagChargeConeInR05K110_;
  double BsTagChargeConeInR05K125_;
  double BsTagChargeConeInR05K150_;
  double BsTagChargeConeInR05K175_;
  double BsTagChargeConeOutR05K025_;
  double BsTagChargeConeOutR05K050_;
  double BsTagChargeConeOutR05K075_;
  double BsTagChargeConeOutR05K100_;
  double BsTagChargeConeOutR05K110_;
  double BsTagChargeConeOutR05K125_;
  double BsTagChargeConeOutR05K150_;
  double BsTagChargeConeOutR05K175_;
  int    BsTagMuJet_;
  double BsTagMuJetP_;
  double BsTagMuJetPt_;
  double BsTagMuJetEta_;
  double BsTagMuJetPhi_;
  double BsTagMuJetEnergy_;
  double BsTagMuJetMass_;
  double BsTagMuJetCSV_;
  double BsTagMuJetBDeltaR_;
  int    BsTagMuJetParton_;
  int    BsTagMCCode_;
  int    BsTagMCSimpleCode_;
  int    BsTagAncestorId_;

  int    BdTagGENID_;
  int    BdTag_;
  double BdTagP_;
  double BdTagPt_;
  double BdTagEta_;
  double BdTagPhi_;
  double BdTagIP_;
  int    BdTagCharge_;
  int    BdTagPF_;
  int    BdTagLoose_;
  int    BdTagSoft_;
  int    BdTagTight_;
  int    BdTagTracker_;
  int    BdTagGlobal_;
  int    BdTagGlobalPromptTight_;
  int    BdTagTrackerArbitrated_;
  double BdTagGlbNormChi2_;
  int    BdTagGlbValidMuonHits_;
  int    BdTagInTrkNValidHits_;
  int    BdTagInTrkNValidPixelHits_;
  double BdTagInTrkNormChi2_;
  int    BdTagNMatches_;
  int    BdTagNMatchedStations_;
  int    BdTagNTrkLayersWithMeas_;
  int    BdTagIsolationValid_;
  int    BdTagPFIsolationValid_;
  double BdTagPFIsolationR04SumChHadPt_;
  double BdTagPFIsolationR04SumChParPt_;
  double BdTagPFIsolationR04SumNeuHadEt_;
  double BdTagPFIsolationR04SumPhoEt_;
  double BdTagPFIsolationR04SumPUPt_;
  double BdTagPFIsoR04Rel_;
  double BdTagPFIsoR04RelPUcorr_;
  double BdTagDxyz_;
  double BdTagDxyzErr_;
  double BdTagDxy_;
  double BdTagDxyErr_;
  int    BdTagChargeDiffRecoB_;
  int    BdTagCPDiffGenB_;
  double BdTagBDeltaR_;
  double BdTagMuJetDeltaR_;
  double BdTagMuJetPtRel_;
  double BdTagMuJetPOverE_;
  double BdTagMuJetPtOverE_;
  double BdTagMuJetPtOverPt_;
  double BdTagChargeConeMuInR03K025_;
  double BdTagChargeConeMuInR03K050_;
  double BdTagChargeConeMuInR03K075_;
  double BdTagChargeConeMuInR03K100_;
  double BdTagChargeConeMuInR03K110_;
  double BdTagChargeConeMuInR03K125_;
  double BdTagChargeConeMuInR03K150_;
  double BdTagChargeConeMuInR03K175_;
  double BdTagChargeConeMuOutR03K025_;
  double BdTagChargeConeMuOutR03K050_;
  double BdTagChargeConeMuOutR03K075_;
  double BdTagChargeConeMuOutR03K100_;
  double BdTagChargeConeMuOutR03K110_;
  double BdTagChargeConeMuOutR03K125_;
  double BdTagChargeConeMuOutR03K150_;
  double BdTagChargeConeMuOutR03K175_;
  double BdTagChargeConeMuInR05K025_;
  double BdTagChargeConeMuInR05K050_;
  double BdTagChargeConeMuInR05K075_;
  double BdTagChargeConeMuInR05K100_;
  double BdTagChargeConeMuInR05K110_;
  double BdTagChargeConeMuInR05K125_;
  double BdTagChargeConeMuInR05K150_;
  double BdTagChargeConeMuInR05K175_;
  double BdTagChargeConeMuOutR05K025_;
  double BdTagChargeConeMuOutR05K050_;
  double BdTagChargeConeMuOutR05K075_;
  double BdTagChargeConeMuOutR05K100_;
  double BdTagChargeConeMuOutR05K110_;
  double BdTagChargeConeMuOutR05K125_;
  double BdTagChargeConeMuOutR05K150_;
  double BdTagChargeConeMuOutR05K175_;
  double BdTagChargeConeMuInR03K025PV_;
  double BdTagChargeConeMuInR03K050PV_;
  double BdTagChargeConeMuInR03K075PV_;
  double BdTagChargeConeMuInR03K100PV_;
  double BdTagChargeConeMuInR03K110PV_;
  double BdTagChargeConeMuInR03K125PV_;
  double BdTagChargeConeMuInR03K150PV_;
  double BdTagChargeConeMuInR03K175PV_;
  double BdTagChargeConeMuOutR03K025PV_;
  double BdTagChargeConeMuOutR03K050PV_;
  double BdTagChargeConeMuOutR03K075PV_;
  double BdTagChargeConeMuOutR03K100PV_;
  double BdTagChargeConeMuOutR03K110PV_;
  double BdTagChargeConeMuOutR03K125PV_;
  double BdTagChargeConeMuOutR03K150PV_;
  double BdTagChargeConeMuOutR03K175PV_;
  double BdTagChargeConeMuInR05K025PV_;
  double BdTagChargeConeMuInR05K050PV_;
  double BdTagChargeConeMuInR05K075PV_;
  double BdTagChargeConeMuInR05K100PV_;
  double BdTagChargeConeMuInR05K110PV_;
  double BdTagChargeConeMuInR05K125PV_;
  double BdTagChargeConeMuInR05K150PV_;
  double BdTagChargeConeMuInR05K175PV_;
  double BdTagChargeConeMuOutR05K025PV_;
  double BdTagChargeConeMuOutR05K050PV_;
  double BdTagChargeConeMuOutR05K075PV_;
  double BdTagChargeConeMuOutR05K100PV_;
  double BdTagChargeConeMuOutR05K110PV_;
  double BdTagChargeConeMuOutR05K125PV_;
  double BdTagChargeConeMuOutR05K150PV_;
  double BdTagChargeConeMuOutR05K175PV_;
  double BdTagChargeConeInR03K025_;
  double BdTagChargeConeInR03K050_;
  double BdTagChargeConeInR03K075_;
  double BdTagChargeConeInR03K100_;
  double BdTagChargeConeInR03K110_;
  double BdTagChargeConeInR03K125_;
  double BdTagChargeConeInR03K150_;
  double BdTagChargeConeInR03K175_;
  double BdTagChargeConeOutR03K025_;
  double BdTagChargeConeOutR03K050_;
  double BdTagChargeConeOutR03K075_;
  double BdTagChargeConeOutR03K100_;
  double BdTagChargeConeOutR03K110_;
  double BdTagChargeConeOutR03K125_;
  double BdTagChargeConeOutR03K150_;
  double BdTagChargeConeOutR03K175_;
  double BdTagChargeConeInR05K025_;
  double BdTagChargeConeInR05K050_;
  double BdTagChargeConeInR05K075_;
  double BdTagChargeConeInR05K100_;
  double BdTagChargeConeInR05K110_;
  double BdTagChargeConeInR05K125_;
  double BdTagChargeConeInR05K150_;
  double BdTagChargeConeInR05K175_;
  double BdTagChargeConeOutR05K025_;
  double BdTagChargeConeOutR05K050_;
  double BdTagChargeConeOutR05K075_;
  double BdTagChargeConeOutR05K100_;
  double BdTagChargeConeOutR05K110_;
  double BdTagChargeConeOutR05K125_;
  double BdTagChargeConeOutR05K150_;
  double BdTagChargeConeOutR05K175_;
  int    BdTagMuJet_;
  double BdTagMuJetP_;
  double BdTagMuJetPt_;
  double BdTagMuJetEta_;
  double BdTagMuJetPhi_;
  double BdTagMuJetEnergy_;
  double BdTagMuJetMass_;
  double BdTagMuJetCSV_;
  double BdTagMuJetBDeltaR_;
  int    BdTagMuJetParton_;
  int    BdTagMCCode_;
  int    BdTagMCSimpleCode_;
  int    BdTagAncestorId_;
  //END Muon Taggging

  //BEGIN ELECTRON TAGGING
  double BpTagEDrGenP_;
  double BpTagEDptGenP_;
  double BpTagEgsfDrGenP_;
  double BpTagEgsfDptGenP_;
  double BpTagEIDNonTrig_;
  double BpTagEIDTrig_;
  double BpTagEIDTrigNoIP_;
  double BpTagEIP_;
  double BpTagEPt_;
  int     BpTagECharge_;
  double BpTagEEta_;
  double BpTagEPhi_;
  double BpTagEP_;
  int     BpTagEGENID_;
  int     BpTagEle_;
  double BpTagEleP_;
  double BpTagElePt_;
  double BpTagEleEta_;
  double BpTagElePhi_;
  int     BpTagEleCharge_;
  double BpTagEleE_;
  int     BpTagElePF_;
  double BpTagEleDxyz_;
  double BpTagEleDxyzErr_;
  double BpTagEleDxy_;
  double BpTagEleDxyErr_;
  int     BpTagEleChargeDiffRecoB_;
  int     BpTagEleCPDiffGenB_;
  double BpTagEleBDeltaR_;
  double BpTagElePFmva_;
  double BpTagElePFIsolationR04ChHadIso_;
  double BpTagElePFIsolationR04NeuHadIso_;
  double BpTagElePFIsolationR04PhoIso_;
  double BpTagElePFIsolationR04PUIso_;
  double BpTagElePFIsoR04Rel_;
  double BpTagElePFIsoR04RelPUcorr_;
  double BpTagEleIdMvaNonTrigV0_;
  double BpTagEleIdMvaTrigV0_;
  double BpTagEleIdMvaTrigNoIPV0_;
  double BpTagEleR9_;
  double BpTagElefBrem_;
  int     BpTagEleisEB_;
  int     BpTagEleisEE_;
  double BpTagEleSigmaIphiIphi_;
  double BpTagEleSigmaIetaIphi_;
  double BpTagEleScSigmaIEtaIEta_;
  double BpTagEleDetaScTrkAtVtx_;
  double BpTagEleDphiScTrkAtVtx_;
  double BpTagEleHadronicOverEm_;
  double BpTagEleIverseER_;
  int     BpTagEleExpInHits_;
  int     BpTagEleIdLoose_;
  int     BpTagEleIdRobustLoose_;
  int     BpTagEleIdTight_;
  int     BpTagEleIdRobustTight_;
  double BpTagEleChargeConeEleInR03K025_;
  double BpTagEleChargeConeEleInR03K050_;
  double BpTagEleChargeConeEleInR03K075_;
  double BpTagEleChargeConeEleInR03K100_;
  double BpTagEleChargeConeEleInR03K110_;
  double BpTagEleChargeConeEleInR03K125_;
  double BpTagEleChargeConeEleInR03K150_;
  double BpTagEleChargeConeEleInR03K175_;
  double BpTagEleChargeConeEleOutR03K025_;
  double BpTagEleChargeConeEleOutR03K050_;
  double BpTagEleChargeConeEleOutR03K075_;
  double BpTagEleChargeConeEleOutR03K100_;
  double BpTagEleChargeConeEleOutR03K110_;
  double BpTagEleChargeConeEleOutR03K125_;
  double BpTagEleChargeConeEleOutR03K150_;
  double BpTagEleChargeConeEleOutR03K175_;
  double BpTagEleChargeConeEleInR05K025_;
  double BpTagEleChargeConeEleInR05K050_;
  double BpTagEleChargeConeEleInR05K075_;
  double BpTagEleChargeConeEleInR05K100_;
  double BpTagEleChargeConeEleInR05K110_;
  double BpTagEleChargeConeEleInR05K125_;
  double BpTagEleChargeConeEleInR05K150_;
  double BpTagEleChargeConeEleInR05K175_;
  double BpTagEleChargeConeEleOutR05K025_;
  double BpTagEleChargeConeEleOutR05K050_;
  double BpTagEleChargeConeEleOutR05K075_;
  double BpTagEleChargeConeEleOutR05K100_;
  double BpTagEleChargeConeEleOutR05K110_;
  double BpTagEleChargeConeEleOutR05K125_;
  double BpTagEleChargeConeEleOutR05K150_;
  double BpTagEleChargeConeEleOutR05K175_;
  double BpTagEleChargeConeEleInR03K025PV_;
  double BpTagEleChargeConeEleInR03K050PV_;
  double BpTagEleChargeConeEleInR03K075PV_;
  double BpTagEleChargeConeEleInR03K100PV_;
  double BpTagEleChargeConeEleInR03K110PV_;
  double BpTagEleChargeConeEleInR03K125PV_;
  double BpTagEleChargeConeEleInR03K150PV_;
  double BpTagEleChargeConeEleInR03K175PV_;
  double BpTagEleChargeConeEleOutR03K025PV_;
  double BpTagEleChargeConeEleOutR03K050PV_;
  double BpTagEleChargeConeEleOutR03K075PV_;
  double BpTagEleChargeConeEleOutR03K100PV_;
  double BpTagEleChargeConeEleOutR03K110PV_;
  double BpTagEleChargeConeEleOutR03K125PV_;
  double BpTagEleChargeConeEleOutR03K150PV_;
  double BpTagEleChargeConeEleOutR03K175PV_;
  double BpTagEleChargeConeEleInR05K025PV_;
  double BpTagEleChargeConeEleInR05K050PV_;
  double BpTagEleChargeConeEleInR05K075PV_;
  double BpTagEleChargeConeEleInR05K100PV_;
  double BpTagEleChargeConeEleInR05K110PV_;
  double BpTagEleChargeConeEleInR05K125PV_;
  double BpTagEleChargeConeEleInR05K150PV_;
  double BpTagEleChargeConeEleInR05K175PV_;
  double BpTagEleChargeConeEleOutR05K025PV_;
  double BpTagEleChargeConeEleOutR05K050PV_;
  double BpTagEleChargeConeEleOutR05K075PV_;
  double BpTagEleChargeConeEleOutR05K100PV_;
  double BpTagEleChargeConeEleOutR05K110PV_;
  double BpTagEleChargeConeEleOutR05K125PV_;
  double BpTagEleChargeConeEleOutR05K150PV_;
  double BpTagEleChargeConeEleOutR05K175PV_;
  double BpTagEleChargeConeInR03K025_;
  double BpTagEleChargeConeInR03K050_;
  double BpTagEleChargeConeInR03K075_;
  double BpTagEleChargeConeInR03K100_;
  double BpTagEleChargeConeInR03K110_;
  double BpTagEleChargeConeInR03K125_;
  double BpTagEleChargeConeInR03K150_;
  double BpTagEleChargeConeInR03K175_;
  double BpTagEleChargeConeOutR03K025_;
  double BpTagEleChargeConeOutR03K050_;
  double BpTagEleChargeConeOutR03K075_;
  double BpTagEleChargeConeOutR03K100_;
  double BpTagEleChargeConeOutR03K110_;
  double BpTagEleChargeConeOutR03K125_;
  double BpTagEleChargeConeOutR03K150_;
  double BpTagEleChargeConeOutR03K175_;
  double BpTagEleChargeConeInR05K025_;
  double BpTagEleChargeConeInR05K050_;
  double BpTagEleChargeConeInR05K075_;
  double BpTagEleChargeConeInR05K100_;
  double BpTagEleChargeConeInR05K110_;
  double BpTagEleChargeConeInR05K125_;
  double BpTagEleChargeConeInR05K150_;
  double BpTagEleChargeConeInR05K175_;
  double BpTagEleChargeConeOutR05K025_;
  double BpTagEleChargeConeOutR05K050_;
  double BpTagEleChargeConeOutR05K075_;
  double BpTagEleChargeConeOutR05K100_;
  double BpTagEleChargeConeOutR05K110_;
  double BpTagEleChargeConeOutR05K125_;
  double BpTagEleChargeConeOutR05K150_;
  double BpTagEleChargeConeOutR05K175_;
  int     BpTagEleEleJet_;
  double BpTagEleEleJetP_;
  double BpTagEleEleJetPt_;
  double BpTagEleEleJetEta_;
  double BpTagEleEleJetPhi_;
  double BpTagEleEleJetEnergy_;
  double BpTagEleEleJetMass_;
  double BpTagEleEleJetCSV_;
  double BpTagEleEleJetBDeltaR_;
  double BpTagEleEleJetDeltaR_;
  double BpTagEleEleJetPOverE_;
  double BpTagEleEleJetPtOverE_;
  double BpTagEleEleJetPtOverPt_;
  double BpTagEleEleJetPtRel_;
  int     BpTagEleEleJetParton_;
  int     BpTagEleMCCode_;
  int     BpTagEleMCSimpleCode_;
  int     BpTagEleAncestorId_;
  int     BpTagEleGENID_;

  double BsTagEIDNonTrig_;
  double BsTagEIDTrig_;
  double BsTagEIDTrigNoIP_;
  double BsTagEIP_;
  double BsTagEPt_;
  int     BsTagECharge_;
  double BsTagEEta_;
  double BsTagEPhi_;
  double BsTagEP_;
  int     BsTagEGENID_;
  int     BsTagEle_;
  double BsTagEleP_;
  double BsTagElePt_;
  double BsTagEleEta_;
  double BsTagElePhi_;
  int     BsTagEleCharge_;
  double BsTagEleE_;
  int     BsTagElePF_;
  double BsTagEleDxyz_;
  double BsTagEleDxyzErr_;
  double BsTagEleDxy_;
  double BsTagEleDxyErr_;
  int     BsTagEleChargeDiffRecoB_;
  int     BsTagEleCPDiffGenB_;
  double BsTagEleBDeltaR_;
  double BsTagElePFmva_;
  double BsTagElePFIsolationR04ChHadIso_;
  double BsTagElePFIsolationR04NeuHadIso_;
  double BsTagElePFIsolationR04PhoIso_;
  double BsTagElePFIsolationR04PUIso_;
  double BsTagElePFIsoR04Rel_;
  double BsTagElePFIsoR04RelPUcorr_;
  double BsTagEleIdMvaNonTrigV0_;
  double BsTagEleIdMvaTrigV0_;
  double BsTagEleIdMvaTrigNoIPV0_;
  double BsTagEleR9_;
  double BsTagElefBrem_;
  int     BsTagEleisEB_;
  int     BsTagEleisEE_;
  double BsTagEleSigmaIphiIphi_;
  double BsTagEleSigmaIetaIphi_;
  double BsTagEleScSigmaIEtaIEta_;
  double BsTagEleDetaScTrkAtVtx_;
  double BsTagEleDphiScTrkAtVtx_;
  double BsTagEleHadronicOverEm_;
  double BsTagEleIverseER_;
  int     BsTagEleExpInHits_;
  int     BsTagEleIdLoose_;
  int     BsTagEleIdRobustLoose_;
  int     BsTagEleIdTight_;
  int     BsTagEleIdRobustTight_;
  double BsTagEleChargeConeEleInR03K025_;
  double BsTagEleChargeConeEleInR03K050_;
  double BsTagEleChargeConeEleInR03K075_;
  double BsTagEleChargeConeEleInR03K100_;
  double BsTagEleChargeConeEleInR03K110_;
  double BsTagEleChargeConeEleInR03K125_;
  double BsTagEleChargeConeEleInR03K150_;
  double BsTagEleChargeConeEleInR03K175_;
  double BsTagEleChargeConeEleOutR03K025_;
  double BsTagEleChargeConeEleOutR03K050_;
  double BsTagEleChargeConeEleOutR03K075_;
  double BsTagEleChargeConeEleOutR03K100_;
  double BsTagEleChargeConeEleOutR03K110_;
  double BsTagEleChargeConeEleOutR03K125_;
  double BsTagEleChargeConeEleOutR03K150_;
  double BsTagEleChargeConeEleOutR03K175_;
  double BsTagEleChargeConeEleInR05K025_;
  double BsTagEleChargeConeEleInR05K050_;
  double BsTagEleChargeConeEleInR05K075_;
  double BsTagEleChargeConeEleInR05K100_;
  double BsTagEleChargeConeEleInR05K110_;
  double BsTagEleChargeConeEleInR05K125_;
  double BsTagEleChargeConeEleInR05K150_;
  double BsTagEleChargeConeEleInR05K175_;
  double BsTagEleChargeConeEleOutR05K025_;
  double BsTagEleChargeConeEleOutR05K050_;
  double BsTagEleChargeConeEleOutR05K075_;
  double BsTagEleChargeConeEleOutR05K100_;
  double BsTagEleChargeConeEleOutR05K110_;
  double BsTagEleChargeConeEleOutR05K125_;
  double BsTagEleChargeConeEleOutR05K150_;
  double BsTagEleChargeConeEleOutR05K175_;
  double BsTagEleChargeConeEleInR03K025PV_;
  double BsTagEleChargeConeEleInR03K050PV_;
  double BsTagEleChargeConeEleInR03K075PV_;
  double BsTagEleChargeConeEleInR03K100PV_;
  double BsTagEleChargeConeEleInR03K110PV_;
  double BsTagEleChargeConeEleInR03K125PV_;
  double BsTagEleChargeConeEleInR03K150PV_;
  double BsTagEleChargeConeEleInR03K175PV_;
  double BsTagEleChargeConeEleOutR03K025PV_;
  double BsTagEleChargeConeEleOutR03K050PV_;
  double BsTagEleChargeConeEleOutR03K075PV_;
  double BsTagEleChargeConeEleOutR03K100PV_;
  double BsTagEleChargeConeEleOutR03K110PV_;
  double BsTagEleChargeConeEleOutR03K125PV_;
  double BsTagEleChargeConeEleOutR03K150PV_;
  double BsTagEleChargeConeEleOutR03K175PV_;
  double BsTagEleChargeConeEleInR05K025PV_;
  double BsTagEleChargeConeEleInR05K050PV_;
  double BsTagEleChargeConeEleInR05K075PV_;
  double BsTagEleChargeConeEleInR05K100PV_;
  double BsTagEleChargeConeEleInR05K110PV_;
  double BsTagEleChargeConeEleInR05K125PV_;
  double BsTagEleChargeConeEleInR05K150PV_;
  double BsTagEleChargeConeEleInR05K175PV_;
  double BsTagEleChargeConeEleOutR05K025PV_;
  double BsTagEleChargeConeEleOutR05K050PV_;
  double BsTagEleChargeConeEleOutR05K075PV_;
  double BsTagEleChargeConeEleOutR05K100PV_;
  double BsTagEleChargeConeEleOutR05K110PV_;
  double BsTagEleChargeConeEleOutR05K125PV_;
  double BsTagEleChargeConeEleOutR05K150PV_;
  double BsTagEleChargeConeEleOutR05K175PV_;
  double BsTagEleChargeConeInR03K025_;
  double BsTagEleChargeConeInR03K050_;
  double BsTagEleChargeConeInR03K075_;
  double BsTagEleChargeConeInR03K100_;
  double BsTagEleChargeConeInR03K110_;
  double BsTagEleChargeConeInR03K125_;
  double BsTagEleChargeConeInR03K150_;
  double BsTagEleChargeConeInR03K175_;
  double BsTagEleChargeConeOutR03K025_;
  double BsTagEleChargeConeOutR03K050_;
  double BsTagEleChargeConeOutR03K075_;
  double BsTagEleChargeConeOutR03K100_;
  double BsTagEleChargeConeOutR03K110_;
  double BsTagEleChargeConeOutR03K125_;
  double BsTagEleChargeConeOutR03K150_;
  double BsTagEleChargeConeOutR03K175_;
  double BsTagEleChargeConeInR05K025_;
  double BsTagEleChargeConeInR05K050_;
  double BsTagEleChargeConeInR05K075_;
  double BsTagEleChargeConeInR05K100_;
  double BsTagEleChargeConeInR05K110_;
  double BsTagEleChargeConeInR05K125_;
  double BsTagEleChargeConeInR05K150_;
  double BsTagEleChargeConeInR05K175_;
  double BsTagEleChargeConeOutR05K025_;
  double BsTagEleChargeConeOutR05K050_;
  double BsTagEleChargeConeOutR05K075_;
  double BsTagEleChargeConeOutR05K100_;
  double BsTagEleChargeConeOutR05K110_;
  double BsTagEleChargeConeOutR05K125_;
  double BsTagEleChargeConeOutR05K150_;
  double BsTagEleChargeConeOutR05K175_;
  int     BsTagEleEleJet_;
  double BsTagEleEleJetP_;
  double BsTagEleEleJetPt_;
  double BsTagEleEleJetEta_;
  double BsTagEleEleJetPhi_;
  double BsTagEleEleJetEnergy_;
  double BsTagEleEleJetMass_;
  double BsTagEleEleJetCSV_;
  double BsTagEleEleJetBDeltaR_;
  double BsTagEleEleJetDeltaR_;
  double BsTagEleEleJetPOverE_;
  double BsTagEleEleJetPtOverE_;
  double BsTagEleEleJetPtOverPt_;
  double BsTagEleEleJetPtRel_;
  int     BsTagEleEleJetParton_;
  int     BsTagEleMCCode_;
  int     BsTagEleMCSimpleCode_;
  int     BsTagEleAncestorId_;
  int     BsTagEleGENID_;

  double BdTagEIDNonTrig_;
  double BdTagEIDTrig_;
  double BdTagEIDTrigNoIP_;
  double BdTagEIP_;
  double BdTagEPt_;
  int     BdTagECharge_;
  double BdTagEEta_;
  double BdTagEPhi_;
  double BdTagEP_;
  int     BdTagEGENID_;
  int     BdTagEle_;
  double BdTagEleP_;
  double BdTagElePt_;
  double BdTagEleEta_;
  double BdTagElePhi_;
  int     BdTagEleCharge_;
  double BdTagEleE_;
  int     BdTagElePF_;
  double BdTagEleDxyz_;
  double BdTagEleDxyzErr_;
  double BdTagEleDxy_;
  double BdTagEleDxyErr_;
  int     BdTagEleChargeDiffRecoB_;
  int     BdTagEleCPDiffGenB_;
  double BdTagEleBDeltaR_;
  double BdTagElePFmva_;
  double BdTagElePFIsolationR04ChHadIso_;
  double BdTagElePFIsolationR04NeuHadIso_;
  double BdTagElePFIsolationR04PhoIso_;
  double BdTagElePFIsolationR04PUIso_;
  double BdTagElePFIsoR04Rel_;
  double BdTagElePFIsoR04RelPUcorr_;
  double BdTagEleIdMvaNonTrigV0_;
  double BdTagEleIdMvaTrigV0_;
  double BdTagEleIdMvaTrigNoIPV0_;
  double BdTagEleR9_;
  double BdTagElefBrem_;
  int     BdTagEleisEB_;
  int     BdTagEleisEE_;
  double BdTagEleSigmaIphiIphi_;
  double BdTagEleSigmaIetaIphi_;
  double BdTagEleScSigmaIEtaIEta_;
  double BdTagEleDetaScTrkAtVtx_;
  double BdTagEleDphiScTrkAtVtx_;
  double BdTagEleHadronicOverEm_;
  double BdTagEleIverseER_;
  int     BdTagEleExpInHits_;
  int     BdTagEleIdLoose_;
  int     BdTagEleIdRobustLoose_;
  int     BdTagEleIdTight_;
  int     BdTagEleIdRobustTight_;
  double BdTagEleChargeConeEleInR03K025_;
  double BdTagEleChargeConeEleInR03K050_;
  double BdTagEleChargeConeEleInR03K075_;
  double BdTagEleChargeConeEleInR03K100_;
  double BdTagEleChargeConeEleInR03K110_;
  double BdTagEleChargeConeEleInR03K125_;
  double BdTagEleChargeConeEleInR03K150_;
  double BdTagEleChargeConeEleInR03K175_;
  double BdTagEleChargeConeEleOutR03K025_;
  double BdTagEleChargeConeEleOutR03K050_;
  double BdTagEleChargeConeEleOutR03K075_;
  double BdTagEleChargeConeEleOutR03K100_;
  double BdTagEleChargeConeEleOutR03K110_;
  double BdTagEleChargeConeEleOutR03K125_;
  double BdTagEleChargeConeEleOutR03K150_;
  double BdTagEleChargeConeEleOutR03K175_;
  double BdTagEleChargeConeEleInR05K025_;
  double BdTagEleChargeConeEleInR05K050_;
  double BdTagEleChargeConeEleInR05K075_;
  double BdTagEleChargeConeEleInR05K100_;
  double BdTagEleChargeConeEleInR05K110_;
  double BdTagEleChargeConeEleInR05K125_;
  double BdTagEleChargeConeEleInR05K150_;
  double BdTagEleChargeConeEleInR05K175_;
  double BdTagEleChargeConeEleOutR05K025_;
  double BdTagEleChargeConeEleOutR05K050_;
  double BdTagEleChargeConeEleOutR05K075_;
  double BdTagEleChargeConeEleOutR05K100_;
  double BdTagEleChargeConeEleOutR05K110_;
  double BdTagEleChargeConeEleOutR05K125_;
  double BdTagEleChargeConeEleOutR05K150_;
  double BdTagEleChargeConeEleOutR05K175_;
  double BdTagEleChargeConeEleInR03K025PV_;
  double BdTagEleChargeConeEleInR03K050PV_;
  double BdTagEleChargeConeEleInR03K075PV_;
  double BdTagEleChargeConeEleInR03K100PV_;
  double BdTagEleChargeConeEleInR03K110PV_;
  double BdTagEleChargeConeEleInR03K125PV_;
  double BdTagEleChargeConeEleInR03K150PV_;
  double BdTagEleChargeConeEleInR03K175PV_;
  double BdTagEleChargeConeEleOutR03K025PV_;
  double BdTagEleChargeConeEleOutR03K050PV_;
  double BdTagEleChargeConeEleOutR03K075PV_;
  double BdTagEleChargeConeEleOutR03K100PV_;
  double BdTagEleChargeConeEleOutR03K110PV_;
  double BdTagEleChargeConeEleOutR03K125PV_;
  double BdTagEleChargeConeEleOutR03K150PV_;
  double BdTagEleChargeConeEleOutR03K175PV_;
  double BdTagEleChargeConeEleInR05K025PV_;
  double BdTagEleChargeConeEleInR05K050PV_;
  double BdTagEleChargeConeEleInR05K075PV_;
  double BdTagEleChargeConeEleInR05K100PV_;
  double BdTagEleChargeConeEleInR05K110PV_;
  double BdTagEleChargeConeEleInR05K125PV_;
  double BdTagEleChargeConeEleInR05K150PV_;
  double BdTagEleChargeConeEleInR05K175PV_;
  double BdTagEleChargeConeEleOutR05K025PV_;
  double BdTagEleChargeConeEleOutR05K050PV_;
  double BdTagEleChargeConeEleOutR05K075PV_;
  double BdTagEleChargeConeEleOutR05K100PV_;
  double BdTagEleChargeConeEleOutR05K110PV_;
  double BdTagEleChargeConeEleOutR05K125PV_;
  double BdTagEleChargeConeEleOutR05K150PV_;
  double BdTagEleChargeConeEleOutR05K175PV_;
  double BdTagEleChargeConeInR03K025_;
  double BdTagEleChargeConeInR03K050_;
  double BdTagEleChargeConeInR03K075_;
  double BdTagEleChargeConeInR03K100_;
  double BdTagEleChargeConeInR03K110_;
  double BdTagEleChargeConeInR03K125_;
  double BdTagEleChargeConeInR03K150_;
  double BdTagEleChargeConeInR03K175_;
  double BdTagEleChargeConeOutR03K025_;
  double BdTagEleChargeConeOutR03K050_;
  double BdTagEleChargeConeOutR03K075_;
  double BdTagEleChargeConeOutR03K100_;
  double BdTagEleChargeConeOutR03K110_;
  double BdTagEleChargeConeOutR03K125_;
  double BdTagEleChargeConeOutR03K150_;
  double BdTagEleChargeConeOutR03K175_;
  double BdTagEleChargeConeInR05K025_;
  double BdTagEleChargeConeInR05K050_;
  double BdTagEleChargeConeInR05K075_;
  double BdTagEleChargeConeInR05K100_;
  double BdTagEleChargeConeInR05K110_;
  double BdTagEleChargeConeInR05K125_;
  double BdTagEleChargeConeInR05K150_;
  double BdTagEleChargeConeInR05K175_;
  double BdTagEleChargeConeOutR05K025_;
  double BdTagEleChargeConeOutR05K050_;
  double BdTagEleChargeConeOutR05K075_;
  double BdTagEleChargeConeOutR05K100_;
  double BdTagEleChargeConeOutR05K110_;
  double BdTagEleChargeConeOutR05K125_;
  double BdTagEleChargeConeOutR05K150_;
  double BdTagEleChargeConeOutR05K175_;
  int     BdTagEleEleJet_;
  double BdTagEleEleJetP_;
  double BdTagEleEleJetPt_;
  double BdTagEleEleJetEta_;
  double BdTagEleEleJetPhi_;
  double BdTagEleEleJetEnergy_;
  double BdTagEleEleJetMass_;
  double BdTagEleEleJetCSV_;
  double BdTagEleEleJetBDeltaR_;
  double BdTagEleEleJetDeltaR_;
  double BdTagEleEleJetPOverE_;
  double BdTagEleEleJetPtOverE_;
  double BdTagEleEleJetPtOverPt_;
  double BdTagEleEleJetPtRel_;
  int     BdTagEleEleJetParton_;
  int     BdTagEleMCCode_;
  int     BdTagEleMCSimpleCode_;
  int     BdTagEleAncestorId_;
  int     BdTagEleGENID_;
  //END ELECTRON TAGGING

  //BEGIN Jet tagging
  int    BpTagJet_;
  double BpTagJetP_;
  double BpTagJetPt_;
  double BpTagJetEta_;
  double BpTagJetPhi_;
  double BpTagJetE_;
  double BpTagJetJP_;
  double BpTagJetJBP_;
  double BpTagJetTCHE_;
  double BpTagJetSSVHE_;
  double BpTagJetCSV_;
  double BpTagJetBDeltaR_;
  double BpTagJetChargeConeTrkInR03K025_;
  double BpTagJetChargeConeTrkInR03K050_;
  double BpTagJetChargeConeTrkInR03K075_;
  double BpTagJetChargeConeTrkInR03K100_;
  double BpTagJetChargeConeTrkInR03K110_;
  double BpTagJetChargeConeTrkInR03K125_;
  double BpTagJetChargeConeTrkInR03K150_;
  double BpTagJetChargeConeTrkInR03K175_;
  double BpTagJetChargeConeTrkInR05K025_;
  double BpTagJetChargeConeTrkInR05K050_;
  double BpTagJetChargeConeTrkInR05K075_;
  double BpTagJetChargeConeTrkInR05K100_;
  double BpTagJetChargeConeTrkInR05K110_;
  double BpTagJetChargeConeTrkInR05K125_;
  double BpTagJetChargeConeTrkInR05K150_;
  double BpTagJetChargeConeTrkInR05K175_;
  double BpTagJetChargeConeTrkInK025_;
  double BpTagJetChargeConeTrkInK050_;
  double BpTagJetChargeConeTrkInK075_;
  double BpTagJetChargeConeTrkInK100_;
  double BpTagJetChargeConeTrkInK110_;
  double BpTagJetChargeConeTrkInK125_;
  double BpTagJetChargeConeTrkInK150_;
  double BpTagJetChargeConeTrkInK175_;
  double BpTagJetChargeConeInR03K025_;
  double BpTagJetChargeConeInR03K050_;
  double BpTagJetChargeConeInR03K075_;
  double BpTagJetChargeConeInR03K100_;
  double BpTagJetChargeConeInR03K110_;
  double BpTagJetChargeConeInR03K125_;
  double BpTagJetChargeConeInR03K150_;
  double BpTagJetChargeConeInR03K175_;
  double BpTagJetChargeConeInR05K025_;
  double BpTagJetChargeConeInR05K050_;
  double BpTagJetChargeConeInR05K075_;
  double BpTagJetChargeConeInR05K100_;
  double BpTagJetChargeConeInR05K110_;
  double BpTagJetChargeConeInR05K125_;
  double BpTagJetChargeConeInR05K150_;
  double BpTagJetChargeConeInR05K175_;
  double BpTagJetChargeConeInK025_;
  double BpTagJetChargeConeInK050_;
  double BpTagJetChargeConeInK075_;
  double BpTagJetChargeConeInK100_;
  double BpTagJetChargeConeInK110_;
  double BpTagJetChargeConeInK125_;
  double BpTagJetChargeConeInK150_;
  double BpTagJetChargeConeInK175_;
  int    BpTagJetParton_;
  double BpTagJetMuonPtRel_;
  double BpTagJetElectronPtRel_;

  int    BsTagJet_;
  double BsTagJetP_;
  double BsTagJetPt_;
  double BsTagJetEta_;
  double BsTagJetPhi_;
  double BsTagJetE_;
  double BsTagJetJP_;
  double BsTagJetJBP_;
  double BsTagJetTCHE_;
  double BsTagJetSSVHE_;
  double BsTagJetCSV_;
  double BsTagJetBDeltaR_;
  double BsTagJetChargeConeTrkInR03K025_;
  double BsTagJetChargeConeTrkInR03K050_;
  double BsTagJetChargeConeTrkInR03K075_;
  double BsTagJetChargeConeTrkInR03K100_;
  double BsTagJetChargeConeTrkInR03K110_;
  double BsTagJetChargeConeTrkInR03K125_;
  double BsTagJetChargeConeTrkInR03K150_;
  double BsTagJetChargeConeTrkInR03K175_;
  double BsTagJetChargeConeTrkInR05K025_;
  double BsTagJetChargeConeTrkInR05K050_;
  double BsTagJetChargeConeTrkInR05K075_;
  double BsTagJetChargeConeTrkInR05K100_;
  double BsTagJetChargeConeTrkInR05K110_;
  double BsTagJetChargeConeTrkInR05K125_;
  double BsTagJetChargeConeTrkInR05K150_;
  double BsTagJetChargeConeTrkInR05K175_;
  double BsTagJetChargeConeTrkInK025_;
  double BsTagJetChargeConeTrkInK050_;
  double BsTagJetChargeConeTrkInK075_;
  double BsTagJetChargeConeTrkInK100_;
  double BsTagJetChargeConeTrkInK110_;
  double BsTagJetChargeConeTrkInK125_;
  double BsTagJetChargeConeTrkInK150_;
  double BsTagJetChargeConeTrkInK175_;
  double BsTagJetChargeConeInR03K025_;
  double BsTagJetChargeConeInR03K050_;
  double BsTagJetChargeConeInR03K075_;
  double BsTagJetChargeConeInR03K100_;
  double BsTagJetChargeConeInR03K110_;
  double BsTagJetChargeConeInR03K125_;
  double BsTagJetChargeConeInR03K150_;
  double BsTagJetChargeConeInR03K175_;
  double BsTagJetChargeConeInR05K025_;
  double BsTagJetChargeConeInR05K050_;
  double BsTagJetChargeConeInR05K075_;
  double BsTagJetChargeConeInR05K100_;
  double BsTagJetChargeConeInR05K110_;
  double BsTagJetChargeConeInR05K125_;
  double BsTagJetChargeConeInR05K150_;
  double BsTagJetChargeConeInR05K175_;
  double BsTagJetChargeConeInK025_;
  double BsTagJetChargeConeInK050_;
  double BsTagJetChargeConeInK075_;
  double BsTagJetChargeConeInK100_;
  double BsTagJetChargeConeInK110_;
  double BsTagJetChargeConeInK125_;
  double BsTagJetChargeConeInK150_;
  double BsTagJetChargeConeInK175_;
  int    BsTagJetParton_;
  double BsTagJetMuonPtRel_;
  double BsTagJetElectronPtRel_;

  int    BdTagJet_;
  double BdTagJetP_;
  double BdTagJetPt_;
  double BdTagJetEta_;
  double BdTagJetPhi_;
  double BdTagJetE_;
  double BdTagJetJP_;
  double BdTagJetJBP_;
  double BdTagJetTCHE_;
  double BdTagJetSSVHE_;
  double BdTagJetCSV_;
  double BdTagJetBDeltaR_;
  double BdTagJetChargeConeTrkInR03K025_;
  double BdTagJetChargeConeTrkInR03K050_;
  double BdTagJetChargeConeTrkInR03K075_;
  double BdTagJetChargeConeTrkInR03K100_;
  double BdTagJetChargeConeTrkInR03K110_;
  double BdTagJetChargeConeTrkInR03K125_;
  double BdTagJetChargeConeTrkInR03K150_;
  double BdTagJetChargeConeTrkInR03K175_;
  double BdTagJetChargeConeTrkInR05K025_;
  double BdTagJetChargeConeTrkInR05K050_;
  double BdTagJetChargeConeTrkInR05K075_;
  double BdTagJetChargeConeTrkInR05K100_;
  double BdTagJetChargeConeTrkInR05K110_;
  double BdTagJetChargeConeTrkInR05K125_;
  double BdTagJetChargeConeTrkInR05K150_;
  double BdTagJetChargeConeTrkInR05K175_;
  double BdTagJetChargeConeTrkInK025_;
  double BdTagJetChargeConeTrkInK050_;
  double BdTagJetChargeConeTrkInK075_;
  double BdTagJetChargeConeTrkInK100_;
  double BdTagJetChargeConeTrkInK110_;
  double BdTagJetChargeConeTrkInK125_;
  double BdTagJetChargeConeTrkInK150_;
  double BdTagJetChargeConeTrkInK175_;
  double BdTagJetChargeConeInR03K025_;
  double BdTagJetChargeConeInR03K050_;
  double BdTagJetChargeConeInR03K075_;
  double BdTagJetChargeConeInR03K100_;
  double BdTagJetChargeConeInR03K110_;
  double BdTagJetChargeConeInR03K125_;
  double BdTagJetChargeConeInR03K150_;
  double BdTagJetChargeConeInR03K175_;
  double BdTagJetChargeConeInR05K025_;
  double BdTagJetChargeConeInR05K050_;
  double BdTagJetChargeConeInR05K075_;
  double BdTagJetChargeConeInR05K100_;
  double BdTagJetChargeConeInR05K110_;
  double BdTagJetChargeConeInR05K125_;
  double BdTagJetChargeConeInR05K150_;
  double BdTagJetChargeConeInR05K175_;
  double BdTagJetChargeConeInK025_;
  double BdTagJetChargeConeInK050_;
  double BdTagJetChargeConeInK075_;
  double BdTagJetChargeConeInK100_;
  double BdTagJetChargeConeInK110_;
  double BdTagJetChargeConeInK125_;
  double BdTagJetChargeConeInK150_;
  double BdTagJetChargeConeInK175_;
  int    BdTagJetParton_;
  double BdTagJetMuonPtRel_;
  double BdTagJetElectronPtRel_;
  //END Jet tagging

  //BEGIN SV tagging
  int    BpTagJetSV_;
  double BpTagJetSVPt_;
  double BpTagJetSVEta_;
  double BpTagJetSVPhi_;
  double BpTagJetSVM_;
  double BpTagJetSVChi2Norm_;
  int    BpTagJetSVnTrk_;
  double BpTagJetSVFlightL3D_;
  double BpTagJetSVFlightL3Derr_;
  double BpTagJetSVFlightL2D_;
  double BpTagJetSVFlightL2Derr_;
  double BpTagJetSVChargeConeK025_;
  double BpTagJetSVChargeConeK050_;
  double BpTagJetSVChargeConeK075_;
  double BpTagJetSVChargeConeK100_;
  double BpTagJetSVChargeConeK110_;
  double BpTagJetSVChargeConeK125_;
  double BpTagJetSVChargeConeK150_;
  double BpTagJetSVChargeConeK175_;
  int    BpTagJetSVCharge_;

  int    BsTagJetSV_;
  double BsTagJetSVPt_;
  double BsTagJetSVEta_;
  double BsTagJetSVPhi_;
  double BsTagJetSVM_;
  double BsTagJetSVChi2Norm_;
  int    BsTagJetSVnTrk_;
  double BsTagJetSVFlightL3D_;
  double BsTagJetSVFlightL3Derr_;
  double BsTagJetSVFlightL2D_;
  double BsTagJetSVFlightL2Derr_;
  double BsTagJetSVChargeConeK025_;
  double BsTagJetSVChargeConeK050_;
  double BsTagJetSVChargeConeK075_;
  double BsTagJetSVChargeConeK100_;
  double BsTagJetSVChargeConeK110_;
  double BsTagJetSVChargeConeK125_;
  double BsTagJetSVChargeConeK150_;
  double BsTagJetSVChargeConeK175_;
  int    BsTagJetSVCharge_;

  int    BdTagJetSV_;
  double BdTagJetSVPt_;
  double BdTagJetSVEta_;
  double BdTagJetSVPhi_;
  double BdTagJetSVM_;
  double BdTagJetSVChi2Norm_;
  int    BdTagJetSVnTrk_;
  double BdTagJetSVFlightL3D_;
  double BdTagJetSVFlightL3Derr_;
  double BdTagJetSVFlightL2D_;
  double BdTagJetSVFlightL2Derr_;
  double BdTagJetSVChargeConeK025_;
  double BdTagJetSVChargeConeK050_;
  double BdTagJetSVChargeConeK075_;
  double BdTagJetSVChargeConeK100_;
  double BdTagJetSVChargeConeK110_;
  double BdTagJetSVChargeConeK125_;
  double BdTagJetSVChargeConeK150_;
  double BdTagJetSVChargeConeK175_;
  int    BdTagJetSVCharge_;
  //END SV tagging

  int    TrackMultiplicity_ ;
  int    TrackMultiplicityBp_ ;
  int    TrackMultiplicityBd_ ;
  int    MuonMultiplicity_ ;
  int    ElectronMultiplicity_;

  int    BdMuonCat1_;
  int    BdMuonCat2_;
  double BplusM_fit_;
  double BplusVtxProb_;
  double BplusChi2_;
  double BplusPt_;
  double BplusPtot_;
  double KplusPt_;
  double KplusPtot_;
  double BplusMu1Pt_;
  double BplusMu2Pt_;
  double BpJpsiVtxProb_;
  double BpCosDeltaAlpha_;
  double BpMuMuDCA_;
  double BpMuMuDistance_;
  double BpMuMuDistanceSigma_;
  double BpMuDr1_;
  double BpMuDr2_;
  int    BpMuonCat1_;
  int    BpMuonCat2_;
  double BplusMu1Ptot_;
  double BplusMu2Ptot_;
  double BplusEta_;
  double BplusPhi_;
  double JpsiMass_bplus_;
  double JpsiPt_bplus_;
  int    BplusPVindex_;
  double BpCt2DPVCosTheta_;
  double BpCtErr2DCostheta_;
  double IP3DKandJpsiVtx_;
  double IP3DKandJpsiVtxErr_;
  int    BpmatchDoubleMu01_;
  int    BpmatchDoubleMu02_;
  int    BpmatchDoubleMu41_;
  int    BpmatchDoubleMu42_;
  int    BpmatchDoubleMu01DiMuon0_;
  int    BpmatchDoubleMu02DiMuon0_;
  int    BplusKmcId_;
  int    BplusKmomId_;
  int    BplusMu1mcId_;
  int    BplusMu1momId_;
  int    BplusMu1gmomId_;
  int    BplusMu2mcId_;
  int    BplusMu2momId_;
  int    BplusMu2gmomId_;
  int    isMatchedBplus_;
  int    BplusDecayChannel_;

  double BcP_ ;
  double BcCosAlpha_ ;
  double BcIP3D_ ;
  double BcCt_ ;
  double BcM_;
  double BcMC_;
  double BcAng_;
  double BcAngPi_;
  double BcProb_;
  double BctrackPt_;

  int    runNumber_;
  int    PUinteraction_;
  int    EleRecoMCmother1_;
  int    EleRecoMC1_;
  unsigned int eventNumber_;
  int    lumiSection_;

  int    triggerbit_HLTmu3Tk_;
  int    triggerbit_HLTmu5_;
  int    triggerbit_HLTdoubleIsoMu3_;
  int    triggerbit_HLTdoubleMu3_;
  int    triggerbit_HLTdoubleMu0_;
  int    triggerbit_HLTL1DoubleMuOpen_;
  int    triggerbit_HLTmu7_;
  int    triggerbit_HLTMu0Track0Jpsi_;
  int    triggerbit_HLTL1DoubleMuOpenTight_;
  int    triggerbit_HLT_DoubleMu3_Jpsi_v2_;
  int    triggerbit_HLT_DoubleMu3_Jpsi_v2MC_;
  int    triggerbit_HLT_DoubleMu3_Quarkonium_v2_;
  int    triggerbit_HLT_DoubleMu3_Quarkonium_v2MC_;
  int    triggerbit_HLT_DoubleMu3_Quarkonium_v1_;
  int    triggerbit_Jpsi_Displaced_v1_;
  int    triggerbit_Jpsi_Displaced_v1MC_;
  int    triggerbit_7Jpsi_Displaced_v1_;
  int    triggerbit_7Jpsi_Displaced_v2_;
  int    triggerbit_7Jpsi_Displaced_v3_;
  int    triggerbit_3p5Jpsi_Displaced_v2_;
  int    triggerbit_4Jpsi_Displaced_v1_;
  int    triggerbit_4Jpsi_Displaced_v4_;
  int    triggerbit_4Jpsi_Displaced_v5_;
  int    triggerbit_5Jpsi_Displaced_v1_;
  int    triggerbit_5Jpsi_Displaced_v2_;
  int    triggerbit_5Jpsi_Displaced_v4_;
  int    triggerbit_5Jpsi_Displaced_v5_;
  int    triggerbit_Dimuon0_Jpsi_v1_;
  int    triggerbit_Dimuon0_Jpsi_v3_;
  int    triggerbit_Dimuon0_Jpsi_v5_;
  int    triggerbit_Dimuon0_Jpsi_v6_;
  int    triggerbit_Dimuon0_Jpsi_v9_;
  int    triggerbit_Dimuon0_Jpsi_v10_;
  int    triggerbit_Dimuon10_Barrel_;
  int    triggerbit_Dimuon13_Barrel_;
  int    triggerbit_Dimuon0_Jpsi_Muon_v15_;
  int    triggerbit_4Jpsi_Displaced_v9_;
  int    triggerbit_4Jpsi_Displaced_v10_;
  int    triggerbit_4Jpsi_Displaced_v11_;
  int    triggerbit_4Jpsi_Displaced_v12_;

  int    matchL11_ ;
  int    matchL12_ ;
  int    match2mu01_ ;
  int    match2mu02_ ;
  int    match1mu01_ ;
  int    match1mu02_ ;
  int    matchDoubleMu31J_ ;
  int    matchDoubleMu32J_ ;
  int    matchDoubleMu31Q_ ;
  int    matchDoubleMu32Q_ ;
  int    matchDoubleMu71_ ;
  int    matchDoubleMu72_ ;
  int    matchDoubleMu41_ ;
  int    matchDoubleMu42_ ;
  int    matchDoubleMu51_ ;
  int    matchDoubleMu52_ ;
  int    matchDoubleMu01_ ;
  int    matchDoubleMu02_ ;
  int    matchDoubleMu101_ ;
  int    matchDoubleMu102_ ;
  int    matchDoubleMu131_ ;
  int    matchDoubleMu132_ ;
  int    match2mu31_ ;
  int    match2mu32_ ;
  int    matchmu0tk01_;
  int    matchmu0tk02_;
  int    matchFilterJpsi1_;
  int    matchFilterJpsi2_;
  int    BdmatchL11_ ;
  int    BdmatchL12_ ;
  int    Bdmatch2mu01_ ;
  int    Bdmatch2mu02_ ;
  int    Bdmatch2mu31_ ;
  int    Bdmatch2mu32_ ;
  int    Bdmatch1mu01_ ;
  int    Bdmatch1mu02_ ;
  int    BdmatchDoubleMu31Q_ ;
  int    BdmatchDoubleMu32Q_ ;
  int    BdmatchDoubleMu71_ ;
  int    BdmatchDoubleMu72_ ;
  int    BdmatchDoubleMu41_ ;
  int    BdmatchDoubleMu42_ ;
  int    BdmatchDoubleMu51_ ;
  int    BdmatchDoubleMu52_ ;
  int    BdmatchDoubleMu01_ ;
  int    BdmatchDoubleMu02_ ;
  int    BdmatchDoubleMu101_ ;
  int    BdmatchDoubleMu102_ ;
  int    BdmatchDoubleMu131_ ;
  int    BdmatchDoubleMu132_ ;
  int    matchDoubleMu121_ ;
  int    matchDoubleMu122_ ;

  int    MuonType_;

  int    isPV_;
  int    isBS_;
  int    NVertices_;

  int    ihaveajpsi_;
  int    BsCowboy_;
  int    BdCowboy_;
  double BsPhiVtxProb_;
  int    BsMu1QualityG_;
  int    BsMu2QualityG_;
  int    BsMu1QualityT_;
  int    BsMu2QualityT_;
  int    BdMu1QualityG_;
  int    BdMu2QualityG_;
  int    BdMu1QualityT_;
  int    BdMu2QualityT_;

  double BSx_ ;
  double BSy_ ;
  double BSz_ ;
  double BSdx_ ;
  double BSdy_ ;
  double BSdz_ ;
  double BSsigmaZ_ ;
  double BSdsigmaZ_ ;
  double PVx_ ;
  double PVy_ ;
  double PVz_ ;
  double PVerrx_ ;
  double PVerry_ ;
  double PVerrz_ ;

  double JpsiVtxProb_;
  double CosDeltaAlpha_;
  double MuMuDCA_;
  double MuMuDistance_;
  double MuMuDistanceSigma_;
  double MuDr1_;
  double MuDr2_;
  double BdJpsiVtxProb_;
  double BdCosDeltaAlpha_;
  double BdMuMuDCA_;
  double BdMuMuDistance_;
  double BdMuMuDistanceSigma_;
  double BdMuDr1_;
  double BdMuDr2_;


  double PVx_refit_;
  double PVy_refit_;
  double PVz_refit_;
  double PVerrx_refit_;
  double PVerry_refit_;
  double PVerrz_refit_;


  double JpsiM_alone_;
  double JpsiPhi_alone_;
  double JpsiEta_alone_;
  double JpsiPt_alone_;
  double JpsiMu1Pt_alone_;
  double JpsiMu2Pt_alone_;
  double JpsiMu1Phi_alone_;
  double JpsiMu2Phi_alone_;
  double JpsiMu1Eta_alone_;
  double JpsiMu2Eta_alone_;
  int    MuonCat1_;
  int    MuonCat2_;
  int    JpsiMuon1Cat_alone_;
  int    JpsiMuon2Cat_alone_;
  int    BdJpsiMuon1Cat_alone_;
  int    BdJpsiMuon2Cat_alone_;

  int    Mu1GlobalMuonPromptTight_;
  int    Mu2GlobalMuonPromptTight_;
  int    Mu1TrackerMuonArbitrated_;
  int    Mu1TMLastStationTight_;
  int    Mu1TMOneStationTight_;
  int    Mu1TMLastStationOptimizedLowPtTight_;
  int    Mu1TMLastStationAngTight_;
  int    Mu1TMOneStationAngTight_;
  int    Mu1TMLastStationOptimizedBarrelLowPtTight_;
  int    Mu2TrackerMuonArbitrated_;
  int    Mu2TMLastStationTight_;
  int    Mu2TMOneStationTight_;
  int    Mu2TMLastStationOptimizedLowPtTight_;
  int    Mu2TMLastStationAngTight_;
  int    Mu2TMOneStationAngTight_;
  int    Mu2TMLastStationOptimizedBarrelLowPtTight_;



  double JpsiMu1d0_alone_;
  double JpsiMu2d0_alone_;
  double JpsiMu1dz_alone_;
  double JpsiMu2dz_alone_;
  int    JpsiMu1ndof_alone_;
  int    JpsiMu2ndof_alone_;
  double JpsiMu1chi2_alone_;
  double JpsiMu2chi2_alone_;
  int    JpsiMu1nHits_alone_;
  int    JpsiMu2nHits_alone_;
  int    JpsiMu1nPixHits_alone_;
  int    JpsiMu2nPixHits_alone_;

  double K1Pt_beffit_;
  double K1Pz_beffit_;
  double K1Eta_beffit_;
  double K1Phi_beffit_;
  double K2Pt_beffit_;
  double K2Pz_beffit_;
  double K2Eta_beffit_;
  double K2Phi_beffit_;

  double Mu1Pt_beffit_;
  double Mu1Pz_beffit_;
  double Mu1Eta_beffit_;
  double Mu1Phi_beffit_;
  double Mu2Pt_beffit_;
  double Mu2Pz_beffit_;
  double Mu2Eta_beffit_;
  double Mu2Phi_beffit_;
  double BdMu1Pt_beffit_;
  double BdMu1Pz_beffit_;
  double BdMu1Eta_beffit_;
  double BdMu1Phi_beffit_;
  double BdMu2Pt_beffit_;
  double BdMu2Pz_beffit_;
  double BdMu2Eta_beffit_;
  double BdMu2Phi_beffit_;

  double BsFitChi2_;
  int    BsFitNdof_;

  double BsFitVtxProb_;

  double BsFitM_;
  double K1Pt_fit_;
  double K2Pt_fit_;
  double PhiM_fit_;
  double BsFitEta_;
  double BsFitPt_;
  double BsFitPz_;
  double BsFitPhi_;

  double BsFitVtx_x_;
  double BsFitVtx_y_;
  double BsFitVtx_z_;

  double BsM_nofit_;
  double BsPhi_nofit_;
  double BsEta_nofit_;
  double BsPt_nofit_;
  double BsPz_nofit_;

  double JpsiM_nofit_;
  double JpsiPhi_nofit_;
  double JpsiEta_nofit_;
  double JpsiPt_nofit_;
  double JpsiPz_nofit_;
  double BdJpsiM_nofit_;
  double BdJpsiPhi_nofit_;
  double BdJpsiEta_nofit_;
  double BdJpsiPt_nofit_;
  double BdJpsiPz_nofit_;
  int BsSoftMuon1_;
  int BsSoftMuon2_;

  double PhiM_nofit_;
  double PhiPhi_nofit_;
  double PhiEta_nofit_;
  double PhiPt_nofit_;
  double PhiPz_nofit_;

  double costhetaMC_[10];
  double phiMC_[10];
  double cospsiMC_[10];
  double BscosthetaMC_;
  double BsphiMC_;
  double BscospsiMC_;

  double K1Pt_nofit_;
  double K1Pz_nofit_;
  double K1Eta_nofit_;
  double K1Phi_nofit_;
  int    K1Key_nofit_;
  double K2Eta_nofit_;
  double K2Pt_nofit_;
  double K2Pz_nofit_;
  double K2Phi_nofit_;
  int    K2Key_nofit_;

  double K1Chi2_;
  int    K1nHits_;
  double K2Chi2_;
  int    K2nHits_;
  int    K1pixH_;
  int    K1trkH_;
  int    K2pixH_;
  int    K2trkH_;

  double Mu1Chi2_;
  int    Mu1nHits_;
  double Mu2Chi2_;
  int    Mu2nHits_;
  int    Mu1pixH_;
  int    Mu1trkH_;
  int    Mu2pixH_;
  int    Mu2trkH_;

  double Mu1d0_;
  double Mu2d0_;
  double Mu1dz_;
  double Mu2dz_;

  double costheta_;
  double phi_;
  double cospsi_;
  double Bdcostheta_;
  double Bdphi_;
  double Bdcospsi_;
  double BdcosthetaMC_;
  double BdphiMC_;
  double BdcospsiMC_;
  double AngleBsDecayLength_;

  int    isMatched_;
  int    isMatchedBd_;

  double BsLxy_;
  double BsLxyErr_;

  double BsCt_;
  double BsCt3D_;
  double BsCt2D_;
  double BsCt2DBS_;
  double BdCt2DBS_;
  double BdCt2DMC_;
  double BdCt3DMC_;
  double BsCtMPV_;
  double BsCt3Drefit_;
  double BsCt2Drefit_;
  double BsCtMPVrefit_;
  double BsCtErr_;
  double BsCtErr3D_;
  double BsCtErr2D_;
  double BsCtErr2DBS_;
  double BdCtErr2DBS_;
  double BsCtErr2D2_;
  double BsCtErrMPV_;
  double BsCtErr3Drefit_;
  double BsCtErr2Drefit_;
  double BsCtErrMPVrefit_;

  double BsErrX_;
  double BsErrY_;
  double BsErrXY_;

  int    JpsiNumberOfCandidates_;
  int    PhiNumberOfCandidatesBeforeFit_;
  int    BsNumberOfCandidatesBeforeFit_;
  int    BsNumberOfCandidatesAfterFit_;
  int    BsNumberOfCandidatesAfterBestFit_;

  int     K1trkLay_;
  int     K1muDTh_;
  int     K1muCSCh_;
  int     K1muRPCh_;
  int     K2trkLay_;
  int     K2muDTh_;
  int     K2muCSCh_;
  int     K2muRPCh_;
  int     Mu1trkLay_;
  int     Mu1muDTh_;
  int     Mu1muCSCh_;
  int     Mu1muRPCh_;
  int     Mu2trkLay_;
  int     Mu2muDTh_;
  int     Mu2muCSCh_;
  int     Mu2muRPCh_;

  int    K1mcId_;
  int    K1momId_;
  int    K1gmomId_;
  int    K2mcId_;
  int    K2momId_;
  int    K2gmomId_;
  int    Mu1mcId_;
  int    Mu1momId_;
  int    Mu1gmomId_;
  int    Mu2mcId_;
  int    Mu2momId_;
  int    Mu2gmomId_;

  double BsCtErr2DCostheta_;
  Double_t BsCt3DPVCosTheta_;
  Double_t BsCt2DPVCosTheta_;
  double BsDist3d_;
  double BsDist3dErr_;
  double BsTime3d_;
  double BsTime3dErr_;
  double BsDist2d_;
  double BsDist2dErr_;
  double BsTime2d_;
  double BsTime2dErr_;

  double dedxTrk_;
  double errdedxTrk_;
  int    numdedxTrk_;

  int    iPassedCutIdent_;
  int    tagEleCharge_;
  double tagEleP_;
  double tagElePhi_;
  double tagEleEta_;
  double tagEleHcalOverEcal_;
  double tagEleSigmaIetaIeta_;
  int    iPassedCutIdentBd_;
  int    BdTrack1Charge_;


  double K1Fit_par_[7];
  double K2Fit_par_[7];
  double K1Fit_sigX_;
  double K1Fit_sigY_;
  double K1Fit_sigZ_;
  double K2Fit_sigX_;
  double K2Fit_sigY_;
  double K2Fit_sigZ_;
  double K1Fit_sigPX_;
  double K1Fit_sigPY_;
  double K1Fit_sigPZ_;
  double K2Fit_sigPX_;
  double K2Fit_sigPY_;
  double K2Fit_sigPZ_;

  Double_t PVZpos_[30];
  Double_t SVZpos_[30];
  Int_t NTracksInPV_[30];
  Double_t PVAbsPt_[30];
  Double_t BsPtMC_;
  Double_t FirstBsMCZpos_;

  Double_t BsLxy3DMC_;
  Double_t BsLxy2DMC_;
  Double_t BsPMC_;

  double BsCt2DMC_;
  double BsCt3DMC_;
  int    BsIniFlavour_;
  int    BsEndFlavour_;
  int    BdEndFlavour_;
  int    BdIniFlavour_;
  int    BdIniFlavourNew_;
  int    ChannelID_;
  int    BdChannelID_;
  int    GenNumberOfBdecays_;
  int    BmesonsId_[10];
  int    BDauIdMC_[10][15];
  int    BDauDauIdMC_[10][15][10];
  int    GenNumberOfDaughters_[10];
  int    GenNumberOfDaughtersDaughters_[10][15];

  double BDauMMC_[10][15];
  double BDauPtMC_[10][15];
  double BDauPzMC_[10][15];
  double BDauEtaMC_[10][15];
  double BDauPhiMC_[10][15];

  double BDauDauMMC_[10][15][10];
  double BDauDauPtMC_[10][15][10];
  double BDauDauPzMC_[10][15][10];
  double BDauDauEtaMC_[10][15][10];
  double BDauDauPhiMC_[10][15][10];

  double BMMC_[10];
  double BPtMC_[10];
  double BPxMC_[10];
  double BPyMC_[10];
  double BPzMC_[10];
  double BEtaMC_[10];
  double BPhiMC_[10];

  double BVtxMC_x_[10];
  double BVtxMC_y_[10];
  double BVtxMC_z_[10];
  double BSVtxMC_x_[10];
  double BSVtxMC_y_[10];
  double BSVtxMC_z_[10];
  double BLxy_MC_[10];
  double BCt_MC_[10];
  double BCt_MC2D_[10];
  double BCt_MC3D_[10];

  double genBsVtx_z_, genBsVtx_y_, genBsVtx_x_ ;
  double genBsSVtx_z_, genBsSVtx_y_, genBsSVtx_x_ ;

  int    isGenJpsiEvent_;


  // for the Bd->Kstar analysis
  double BdFitChi2_Hyp1_;
  int    BdFitNdof_Hyp1_;

  double BdFitVtxProb_Hyp1_;
  double BdFitVtxProb_;
  int    BdNumberOfCandidates_;

  double BdPVx_refit_   ;
  double BdPVy_refit_   ;
  double BdPVz_refit_   ;
  double BdPVerrx_refit_;
  double BdPVerry_refit_;
  double BdPVerrz_refit_;

  double BdFitM_Hyp1_;
  double BdFitEta_Hyp1_;
  double BdFitPt_Hyp1_;
  double BdFitPz_Hyp1_;
  double BdFitPhi_Hyp1_;

  double BdFitVtx_x_Hyp1_;
  double BdFitVtx_y_Hyp1_;
  double BdFitVtx_z_Hyp1_;

  double BdM_nofit_;
  double BdPhi_nofit_;
  double BdEta_nofit_;
  double BdPt_nofit_;
  double BdPz_nofit_;

  double KstarMass_nofit_Hyp1_ ;
  double KstarMass_nofit_Hyp2_ ;

  double BdK1_kpi_par_Hyp1_[7];
  double BdK2_kpi_par_Hyp1_[7];
  double BdK1_kpi_sigX_Hyp1_;
  double BdK1_kpi_sigY_Hyp1_;
  double BdK1_kpi_sigZ_Hyp1_;
  double BdK2_kpi_sigX_Hyp1_;
  double BdK2_kpi_sigY_Hyp1_;
  double BdK2_kpi_sigZ_Hyp1_;
  double BdK1_kpi_sigPX_Hyp1_;
  double BdK1_kpi_sigPY_Hyp1_;
  double BdK1_kpi_sigPZ_Hyp1_;
  double BdK2_kpi_sigPX_Hyp1_;
  double BdK2_kpi_sigPY_Hyp1_;
  double BdK2_kpi_sigPZ_Hyp1_;

  double BdFitChi2_Hyp2_;
  int    BdFitNdof_Hyp2_;

  double BdFitVtxProb_Hyp2_;


  double BdFitM_Hyp2_;
  double BdFitEta_Hyp2_;
  double BdFitPt_Hyp2_;
  double BdFitPz_Hyp2_;
  double BdFitPhi_Hyp2_;

  double BdFitVtx_x_Hyp2_;
  double BdFitVtx_y_Hyp2_;
  double BdFitVtx_z_Hyp2_;


  double BdK1_kpi_par_Hyp2_[7];
  double BdK2_kpi_par_Hyp2_[7];
  double BdK1_kpi_sigX_Hyp2_;
  double BdK1_kpi_sigY_Hyp2_;
  double BdK1_kpi_sigZ_Hyp2_;
  double BdK2_kpi_sigX_Hyp2_;
  double BdK2_kpi_sigY_Hyp2_;
  double BdK2_kpi_sigZ_Hyp2_;
  double BdK1_kpi_sigPX_Hyp2_;
  double BdK1_kpi_sigPY_Hyp2_;
  double BdK1_kpi_sigPZ_Hyp2_;
  double BdK2_kpi_sigPX_Hyp2_;
  double BdK2_kpi_sigPY_Hyp2_;
  double BdK2_kpi_sigPZ_Hyp2_;


  double BdK1Pt_nofit_  ;
  double BdK1Pz_nofit_  ;
  double BdK1Eta_nofit_ ;
  double BdK1Phi_nofit_ ;
  int    BdK1Key_nofit_  ;
  double BdK2Pt_nofit_  ;
  double BdK2Pz_nofit_  ;
  double BdK2Eta_nofit_ ;
  double BdK2Phi_nofit_ ;
  int    BdK2Key_nofit_  ;

  double BdLxy_;
  double BdLxyErr_;
  double BdErrX_;
  double BdErrY_;
  double BdErrXY_;
  double BdCt_;
  double BdCtErr_;

  double BdDist3d_;
  double BdDist3dErr_;
  double BdTime3d_;
  double BdTime3dErr_;
  double BdDist2d_;
  double BdDist2dErr_;
  double BdTime2d_;
  double BdTime2dErr_;
  double BdCt2DPVCosTheta_;
  double Bdt2DPVCosTheta_;	
  double BdCtErr2DCostheta_;
  double BdtErr2DCostheta_;

  int		BdSoftMuon1_;
  int 	BdSoftMuon2_;

  int		BdMCKstarKaon_;
  int		BdMCKstarPion_;
  int    BdK1mcId_;
  int    BdK1momId_;
  int    BdK1gmomId_;
  int    BdK2mcId_;
  int    BdK2momId_;
  int    BdK2gmomId_;
  int    BdMu1mcId_;
  int    BdMu1momId_;
  int    BdMu1gmomId_;
  int    BdMu2mcId_;
  int    BdMu2momId_;
  int    BdMu2gmomId_;

  //b jet tagging
  int    BJetParton_;
  double BJetEta_;
  double BJetPhi_;
  double BJetPt_;
  double JetBTagProb_;

  int    BpBJetParton_;
  double BpBJetEta_;
  double BpBJetPhi_;
  double BpBJetPt_;
  double BpJetBTagProb_;

  std::vector<int> *PVTrkCharge_;
  std::vector<float> *PVTrkPt_;
  std::vector<float> *PVTrkEta_;
  std::vector<float> *PVTrkPhi_;

  std::vector<int> *BpPVTrkCharge_;
  std::vector<float> *BpPVTrkPt_;
  std::vector<float> *BpPVTrkEta_;
  std::vector<float> *BpPVTrkPhi_;


  std::vector<int> *BJetTrkCharge_;
  std::vector<float> *BJetTrkPt_;
  std::vector<int> *BpBJetTrkCharge_;
  std::vector<float> *BpBJetTrkPt_;
  //b jet tagging


  TFile* bsFile_;
  TTree* bsTree_;
};

#endif

